name: Pull request check
on:
  push:
    branches:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Run lint checks
        run: |
          poetry run black . --check
          poetry run isort . --check-only
          poetry run flake8 .

          echo 'Linting tests done'
